### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by ruelcedeno** [gerosyab/Guitaroid#1]
Hi! I'm a graphic designer and an open source contributor. How about a new logo for the app?

**Comment by gerosyab** [comment]
Sure. I'd love to see your work.

**Comment by ruelcedeno** [comment]
Here it is. My goal is to create a much simpler minimalistic design which is currently the trend right now. Please let me know what you think. I'll be happy to make adjustments.

![showcase_to_project_owner](https://user-images.githubusercontent.com/37002265/37640881-164126b8-2c4a-11e8-8b5f-877fc723fa03.png)

**Comment by ruelcedeno** [comment]
Hello @gerosyab, here's some mockup for my proposed icon and app launch.

![phone_mockup](https://user-images.githubusercontent.com/37002265/37831856-6be56f2a-2ed9-11e8-8aed-23a8a0080629.png)

**Comment by gerosyab** [comment]
Yeah, it is real cool and simple! Thanks.

Can you make the shape of guitar more like dreadnaught body?

Hear is the comparison of guitar body shape (and dreadnaught body is 'E' in this chart)
https://en.wikipedia.org/wiki/File:Body_Shape_Guitars.jpg

**Comment by ruelcedeno** [comment]
Sure! Thanks. What would you suggest about the color?

**Comment by gerosyab** [comment]
I will use the red as my future app's theme color.

So it would be nice with the color like #E20000, I think.

**Comment by ruelcedeno** [comment]
How about this? I already changed it to dreadnaught body and changed the color to #E20000. What do you think?

![showcase_2](https://user-images.githubusercontent.com/37002265/37876263-08c0a648-3074-11e8-8e7e-175e150929e1.png)

![mockup](https://user-images.githubusercontent.com/37002265/37876265-0c7b9978-3074-11e8-95f4-214b9ae30cd6.png)

**Comment by gerosyab** [comment]
I love it, and I think the first one (flat background with shadow) is the best!!
Thank you very much.

**Comment by ruelcedeno** [comment]
Glad you like it! Let me know which sizes you need and I'll send the files to you.

**Comment by gerosyab** [comment]
I need bigger size over 1024px * 1024px if it is possible, so I can resize and use it as app icon, loading screen and so on.

**Comment by ruelcedeno** [comment]
Okay sir. You can download the vectors and png files [here](https://drive.google.com/drive/folders/1ZLNrtCZBXElii01recQSDOTMsULGp7Cl?usp=sharing). Please let me know if you need anything. I'm excited to see the updated icons in the app. Cheers!

**Comment by gerosyab** [comment]
Ok, I've changed my README. If you want add more information just let me know.
Anyway, I really appreciate about your work. It's really nice.

**Comment by ruelcedeno** [comment]
Happy to hear that. Let me know if you have more graphics request. Looking forward to contributing more.
