### ISSUE TITLE
Guitaroid: App Crashes Upon Multi-tap

### ISSUE THREAD

**Issue by ruelcedeno** [gerosyab/Guitaroid#2]
#### What is Guitaroid?

Guitaroid is an opensource virtual-guitar app. You can download the app [here](https://play.google.com/store/apps/details?id=net.gerosyab.Guitaroid&hl=en).

#### Expected behavior
The app should run as usual upon tapping multiple-strings at the same time in succession. 

#### Actual behavior
The app repeatedly crashes upon tapping multiple strings simultaneously in quick succession (which is a very common action for virtual guitar apps). 

#### How to reproduce
Just download the latest version of the app on Playstore, open it and click Virtual Guitar section. Then tap multiple strings at the same time on any chord. 

- App Version: 1.1.5
- Phone: Samsung Galaxy J7+ (SM-C710F/DS)
- Android Version: 7.1.1

#### Recording Of The Bug
https://youtu.be/Jb9IjQHiGHg
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@ruel.cedeno/guitaroid-app-crashes-upon-multi-tap">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by gerosyab** [comment]
Now I'm trying to renew the guitaroid.
So the problem you mentioned will be fixed in renewed version.
Thanks.
